---
version: "3.8"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.70.0
    labels:
      breeze.description: "Integration required for OTEL/opentelemetry hooks."
    container_name: "breeze-otel-collector"
    command: [--config=/etc/otel-collector-config.yaml]
    volumes:
      - ./configs/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "24318:4318"    # OTLP http receiver
      - "28889:8889"    # Prometheus exporter metrics

  prometheus:
    image: prom/prometheus
    container_name: "breeze-prometheus"
    user: "0"
    ports:
      - "29090:9090"
    volumes:
      - ./configs/prometheus-config.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:8.2.4
    container_name: "breeze-grafana"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_PATHS_PROVISIONING: /grafana/provisioning
    ports:
      - "23000:3000"
    volumes:
      - ./grafana/volume/data:/grafana
      - ./grafana/volume/datasources:/grafana/datasources
      - ./grafana/volume/dashboards:/grafana/dashboards
      - ./grafana/volume/provisioning:/grafana/provisioning

  airflow:
    environment:
      - AIRFLOW__METRICS__OTEL_ON=True
      - AIRFLOW__METRICS__OTEL_HOST=breeze-otel-collector
      - AIRFLOW__METRICS__OTEL_PORT=4318
      - AIRFLOW__METRICS__OTEL_INTERVAL_MILLISECONDS=30000

    depends_on:
      - otel-collector
      - prometheus
      - grafana