---
receivers:
  otlp:
    protocols:
      http:

processors:
  batch:

exporters:
  logging:
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:8889

service:

  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]