---

global:
    scrape_interval: 30s
    evaluation_interval: 30s
    scrape_timeout: 10s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']

    - job_name: 'statsd-exporter'
      static_configs:
          - targets: ['breeze-statsd-exporter:9102']
      tls_config:
          insecure_skip_verify: true

    - job_name: 'otel-collector'
      static_configs:
          - targets: ['breeze-otel-collector:8889']